version: '3.8'

services:
  # Frontend - NuxtJS
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network

  # Backend - Laravel (PHP-FPM)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-backend
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      - database
      - database_test
      - redis
      - redis-test
    networks:
      - app-network

  # Redis - Cache & Session Storage
  redis:
    image: redis:7-alpine
    container_name: ${APP_NAME}-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - app-network

  # Redis - Cache & Session Storage
  redis-test:
    image: redis:7-alpine
    container_name: ${APP_NAME}-redis-test
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    networks:
      - app-network

  # Nginx для Laravel
  nginx-laravel:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx-laravel
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  # Database - PostgreSQL
  database:
    image: postgres:15-alpine
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE:-laravel}
      - POSTGRES_USER=${DB_USERNAME:-laravel}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Database - PostgreSQL
  database_test:
    image: postgres:15-alpine
    container_name: ${APP_NAME}-db-test
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE:-laravel}
      - POSTGRES_USER=${DB_USERNAME:-laravel}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgres_data_test:/var/lib/postgresql/data
    networks:
      - app-network

  # Nginx - Reverse Proxy
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - frontend
      - nginx-laravel
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 